```{r packages}
library(jagsUI)
```

```{r model}
modfile <- tempfile()
writeLines("
model   
{
  # simple one-way ANOVA
  
  # the mean for each of the four locations, drawn from uninformative priors
  globalmean ~ dnorm(0, 1.0E-6)
  for (i in 1:4) {
    a[i] <- globalmean
    tau[i] ~ dgamma(0.001, 0.001)  # uninformative precision
  }


  # for each of the 40 birds sampled
  for (i in 1:40) {
    mean[i] <- a[location[i]]  # the mean depends on the location
    Y[i] ~ dnorm(mean[i], tau[location[i]])
  }
}
           ", con = modfile)
```

```{r data}
data <- list(
  location = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
               3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4),
  Y = c(78, 88, 87, 88, 83, 82, 81, 80, 80, 89, 78, 78, 83, 81, 78, 
        81, 81, 82, 76, 76, 79, 73, 79, 75, 77, 78, 80, 78, 83, 84, 77, 
        69, 75, 70, 74, 83, 80, 75, 76, 75)
)
```

```{r inits}
inits <- function () {
  list(globalmean=70, tau = c(1,1,1,1))
}
```

```{r params}
params <- c("globalmean", "tau")
```

```{r fit}
fit <- autojags(data, inits, params, modfile, n.chains = 4)
```

```{r plot}
plot(fit)
summary(fit$samples)
```

