```{r packages}
library(jagsUI)
```

```{r model}
modfile <- tempfile()
writeLines("
model
{
  a ~ dnorm(0, 1.0E-6)   # priors for the regression parameters
  b ~ dnorm(0, 1.0E-6)
  c ~ dnorm(0, 1.0E-6)
  tau ~ dgamma(0.001, 0.001)

  # for each of the 26 raptors
  # calculate the expected mortality
  for (i in 1:26)
  {
    lp[i] <- a + b*Mass[i] + c*Owl[i]  # mean mortality for raptors with that weight and type
    Mortality[i] ~ dnorm(lp[i], tau)   # actual mortality drawn from a normal distribution
  }
}
           ", con = modfile)
```

```{r data}
data <- list(
  Mass = c(0.37, 0.28, 0.64, 0.14, 1.2, 0.58, 0.9, 0.3, 1.6, 0.885, 0.53, 
           1.2, 0.3, 0.56, 0.7, 1.22, 0.94, 0.14, 0.22, 0.865, 0.95, 2.5, 
           2.3, 3.4, 1.04, 0.565),
  Owl = c(1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
          0, 0, 0, 0, 0, 0),
  Mortality = c(0.33, 0.15, 0.23, 0.3, 0.12, 0.2, 0.15, 0.31, 0.18, 0.3, 0.3, 
                0.25, 0.48, 0.39, 0.31, 0.22, 0.2, 0.48, 0.41, 0.25, 0.26, 0.04, 
                0.035, 0.08, 0.12, 0.25)
)
```

```{r inits}
inits <- function () {
  list(a = 0, b = 0, c = 0, tau = 100)
}
```

```{r params}
params <- c("a", "b", "c", "tau")
```

```{r fit}
fit <- autojags(data, inits, params, modfile, n.chains = 4)
```

```{r plot}
plot(fit)
summary(fit$samples)
```
