In Ellison's paper; 25000 samples after a 25000 burn-in...  Didn't pay enough attention to autocorr plots.

```{r packages}
library(jagsUI)
```

```{r model}
modfile_1 <- tempfile()
writeLines("
model 
{ 
  # for each site
  for (i in 1:N) { 
    richness[i] ~ dpois(mu[i])   # actual richness drawn from Poisson distribution

    # log(mean richness) a linear function of explanatory variables
    log(mu[i]) <- alpha + beta[1] * lat[i] + beta[2] * elev[i] + beta[3] * habitat[i] 
  } 

  # uninformative priors
  #  alpha ~ dnorm(0.0,1.0E-6) 
  #  beta[1] ~ dnorm(0.0,1.0E-6) 
  #  beta[2] ~ dnorm(0.0,1.0E-6) 
  #  beta[3] ~ dnorm(0.0,1.0E-6) 

  # informative priors
  taulat <- 1 / 0.04 / 0.04
  tauelev <- 1 / 0.0003 / 0.0003
  alpha ~ dnorm(0.0, 1.0E-6) 
  beta[1] ~ dnorm(-0.1725, taulat) 
  beta[2] ~ dnorm(-0.0022, tauelev) 
  beta[3] ~ dnorm(0.0, 1.0E-6) 

}
           ", con = modfile_1)
```

```{r model2}
modfile_2 <- tempfile()
writeLines("
model 
{ 
  # uses centred data

  ml <- mean(lat[])
  me <- mean(elev[])

  #  for each site
  for (i in 1:N){ 
    richness[i] ~ dpois(mu[i])   # actual richness drawn from Poisson distribution

    # log(mean richness) a linear function of explanatory variables
    log(mu[i]) <- alpha + beta[1] * (lat[i] - ml) + beta[2] * (elev[i] - me) + beta[3] * habitat[i] 
  } 

  intercept <- alpha - beta[1] * ml - beta[2] * me   # calculates the intercept for un-centred data

  # uninformative priors
  #  alpha ~ dnorm(0.0,1.0E-6) 
  #  beta[1] ~ dnorm(0.0,1.0E-6) 
  #  beta[2] ~ dnorm(0.0,1.0E-6) 
  #  beta[3] ~ dnorm(0.0,1.0E-6) 

  # informative priors
  taulat <- 1 / 0.04 / 0.04
  tauelev <- 1 / 0.0003 / 0.0003
  alpha ~ dnorm(0.0, 1.0E-6) 
  beta[1] ~ dnorm(-0.1725, taulat) 
  beta[2] ~ dnorm(-0.0022, tauelev) 
  beta[3] ~ dnorm(0.0, 1.0E-6) 
}
           ", con = modfile_2)
```

```{r data}
data <- list(
  lat = c(41.97, 42.00, 42.03, 42.05, 42.05, 42.17, 42.19, 42.23, 
          42.27, 42.31, 42.56, 42.57, 42.58, 42.69, 43.33, 44.06, 44.29, 44.33, 
          44.50, 44.55, 44.76, 44.95, 41.97, 42.00, 42.03, 42.05, 42.05, 42.17, 
          42.19, 42.23, 42.27, 42.31, 42.56, 42.57, 42.58, 42.69, 43.33, 44.06, 
          44.29, 44.33, 44.50, 44.55, 44.76, 44.95 ),
  richness = c(6, 16, 18, 17, 9, 
               15, 7, 12, 14, 9, 10, 10, 4, 5, 7, 7, 4, 6, 6, 8, 6, 6, 5, 6, 14,
               7, 4, 8, 2, 3, 4, 8, 8, 4, 2, 7, 2, 3, 3, 2, 3, 2, 5, 5),
  elev = c(389, 8, 152, 1, 210, 78, 47, 491, 121, 95, 274, 335, 543, 323, 158,
           313, 468, 362, 236, 30, 353, 133, 389, 8, 152, 1, 210, 78, 47, 491,
           121, 95, 274, 335, 543, 323, 158, 313, 468, 362, 236, 30, 353, 133), 
  habitat = c(1, 1 , 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0),
  N = 44
)
```

```{r inits}
inits <- function () {
  list(alpha = 0, beta = c(0, 0, 0))
}
```

```{r params}
params <- c("alpha", "beta")
```

```{r fit}
fit1 <- autojags(data, inits, params, modfile, n.chains = 4)

fit2 <- autojags(data, inits, params, modfile, n.chains = 4)
```

```{r plot}
plot(fit1)
summary(fit1$samples)

plot(fit2)
summary(fit2$samples)
```
