```{r packages}
library(jagsUI)
```

```{r model}
modfile <- tempfile()
writeLines("
model
{
  tau <- 1 / 0.2 / 0.2   # env variation

  fem[1] <- 80  # initial pop size

  for(i in 2:N) {

    # enviromental stochasticity 
    envstoch[i] ~ dnorm(0.0, tau)

    # predicted population size
    pred[i] <- fem[i-1] * exp(1.11 - 0.0136 * fem[i-1] + envstoch[i])

    # demographic stochasticity - actual number drawn from Poisson
    fem[i] ~ dpois(pred[i])

    # minimum pop size up to current year is smallest of:
    # the minimum seen up to previous year,
    # and the current population size
  }

  mini <- min(fem)

  # determine if the mini population is 40 or smaller
  q40 <- step(40 - mini)  # step function equals 1 if min<=40

  # determine if the mini population is i or smaller
  for (i in 1:80) {
    q[i] <- step(i - mini)  # step function equals 1 if min<=i
  }
}
           ", con = modfile)
```

```{r data}
data <- list(N = 21)
```

```{r inits}
inits <- NULL
```

```{r params}
params <- c("mini", "q40")
```

```{r fit}
fit <- autojags(data, inits, params, modfile, n.chains = 4)
```

```{r plot}
plot(fit$samples)
summary(fit$samples)
```


