```{r packages}
library(jagsUI)
```

```{r model}
modfile <- tempfile()
writeLines("
model
{
  a ~ dnorm(0, 1.0E-6)  # priors for regression parameters
  b ~ dnorm(0, 1.0E-6)

  sd_study ~ dunif(0, 100)   # prior for sd among studies
  prec_study <- 1 / (sd_study * sd_study)

  sd_spp ~ dunif(0, 100)    # prior for sd among species
  prec_spp <- 1 / (sd_spp * sd_spp)

  # for each of the 28 species
  for(i in 1:28) {
    spp[i] ~ dnorm(0, prec_spp)   # calculate random effect for species
  }

  # for each of the 47 studies
  for(i in 1:47) {
    study[i] ~ dnorm(0, prec_study) # calculate random effect for study

     # expected survival rate
    mean[i] <- a + b * log(weight[i]) + spp[species[i]] + study[i]

    # variation from expectation depends on the reported precision of the study
    prec_within[i] <- 1 / (se[i] * se[i])

    # observed survival rate drawn from a normal distribution
    surv[i] ~ dnorm(mean[i], prec_within[i])
  }

  # making predictions for European dipper
  dip_spp_effect ~ dnorm(0, prec_spp)
  dip_study_effect ~ dnorm(0, prec_study)
  dip_surv <- a + b * log(59.8) + dip_spp_effect + dip_study_effect
}
           ", con = modfile)
```

```{r data}
data <- list(
  species = c(1, 1, 3, 3, 3, 4, 4, 4, 4, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 
              10, 11, 12, 12, 13, 13, 14, 15, 15, 15, 16, 16, 17, 18, 18, 18, 
              19, 20, 21, 22, 23, 24, 25, 26, 26, 27, 28),
  weight = c(21, 21, 9.9, 9.9, 9.9, 19.7, 19.7, 19.7, 19.7, 20.3, 18.2, 
             18.2, 18.2, 113, 113, 113, 61.7, 61.7, 61.7, 115, 10.8, 9.1, 
             13.3, 13.3, 19, 19, 9, 83.2, 83.2, 83.2, 27.7, 27.7, 22, 21.5, 
             21.5, 21.5, 11.2, 12, 27.8, 15.6, 15.3, 13, 40.6, 21.8, 21.8, 
             26.5, 18.3),
  surv = c(0.494, 0.497, 0.319, 0.318, 0.306, 0.458, 0.447, 0.422, 0.451, 
           0.57, 0.484, 0.482, 0.351, 0.668, 0.617, 0.581, 0.572, 0.657, 
           0.581, 0.71, 0.517, 0.372, 0.542, 0.486, 0.577, 0.381, 0.477, 
           0.649, 0.484, 0.48, 0.554, 0.468, 0.433, 0.639, 0.548, 0.489, 
           0.603, 0.54, 0.488, 0.442, 0.395, 0.425, 0.463, 0.444, 0.398, 
           0.561, 0.499),
  se = c(0.031, 0.069, 0.07, 0.068, 0.042, 0.019, 0.05, 0.04, 0.028, 
         0.1, 0.018, 0.038, 0.049, 0.02, 0.01, 0.029, 0.014, 0.048, 0.02, 
         0.05, 0.098, 0.078, 0.01, 0.035, 0.016, 0.044, 0.05, 0.026, 0.01, 
         0.01, 0.023, 0.037, 0.067, 0.021, 0.047, 0.131, 0.075, 0.153, 
         0.04, 0.053, 0.044, 0.06, 0.154, 0.019, 0.049, 0.048, 0.051)
)
```

```{r inits}
inits <- function () {
  list(a = 0.5, b = 0, sd_study = 0.1, sd_spp = 0.1)
}
```

```{r params}
params <- c("a", "b", "sd_study", "sd_spp")
```

```{r fit}
fit <- autojags(data, inits, params, modfile, n.chains = 4)
```

```{r plot}
plot(fit)
summary(fit$samples)
```
